version: "3.0"

services:
  mongo:
    image: mongo:jammy
    restart: on-failure
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: development
    volumes:
      - ../mongo_volume:/data/db

  # Online monitoring tool
  mongo-express:
    image: mongo-express:latest
    depends_on:
      - mongo
    restart: on-failure
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: development
      ME_CONFIG_MONGODB_URL: mongodb://root:development@mongo:27017/
