name: 🚀 Deploy API

on: workflow_dispatch

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v3

      - name: 🔑 Authenticate with Dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: 📦 Build the Docker image
        run: cd api && docker build -t ${{ secrets.DOCKER_USERNAME }}/api .

      - name: 🚀 Push to Dockerhub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/api

      - name: 🔑 End Dockerhub session
        run: docker logout

      - name: 🚀 Update Docker Swarm image
        run: docker service update --image ${{ secrets.DOCKER_USERNAME }}/api api
