name: 🚀 Deploy API

on:
  push:
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v3

      - name: 🔑 Authenticate with Dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: 📦 Build the Docker image
        run: cd api && docker build -t ${{ secrets.DOCKER_USERNAME }}/api:${{ github.ref_name }} .

      - name: 🚀 Push to Dockerhub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/api:${{ github.ref_name } }}

      - name: 🔑 End Dockerhub session
        run: docker logout

      - name: 🚀 Update Docker Swarm image
        run: docker service update --image ${{ secrets.DOCKER_USERNAME }}/api:${{ github.ref_name }} api
